server:
  port: 8080

spring:
  application:
    name: admin-server
  cloud:
    nacos:
      server-addr: 192.168.34.156:8848
      username: nacos
      password: nacos
      config:
        context-path: /nacos
        namespace: 
        file-extension: yml
      discovery:
        namespace: public
  security:
    user:
      name: admin
      password: admin@2022

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
