server:
  port: 8080

spring:
  application:
    name: admin-server
  security:
    user:
      name: admin
      password: admin@2022

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
