package com.demo.domain;
// Generated 2018-9-18 14:14:55 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import org.hibernate.annotations.DynamicInsert;

/**
 * Appnamespace generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "APPNAMESPACE")
@DynamicInsert
public class Appnamespace implements java.io.Serializable {
	private long id;
	private String name;
	private String appid;
	private String format;
	private boolean isPublic;
	private String comment;
	private boolean isDeleted;
	private String datachangeCreatedby;
	private Date datachangeCreatedtime;
	private String datachangeLastmodifiedby;
	private Date datachangeLasttime;

	public Appnamespace() {
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "APPNAMESPACE_SEQ")
	@SequenceGenerator(name = "APPNAMESPACE_SEQ", sequenceName = "APPNAMESPACE_SEQ", allocationSize = 1, initialValue = 1)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "NAME", nullable = false, length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "APPID", nullable = false, length = 32)
	public String getAppid() {
		return this.appid;
	}

	public void setAppid(String appid) {
		this.appid = appid;
	}

	@Column(name = "FORMAT", nullable = false, length = 32)
	public String getFormat() {
		return this.format;
	}

	public void setFormat(String format) {
		this.format = format;
	}

	@Column(name = "ISPUBLIC", nullable = false, length = 1)
	public boolean isPublic() {
		return isPublic;
	}

	public void setPublic(boolean isPublic) {
		this.isPublic = isPublic;
	}

	@Column(name = "comment", nullable = false, length = 64)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "ISDELETED", nullable = false, length = 1)
	public boolean isDeleted() {
		return isDeleted;
	}

	public void setDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "DATACHANGE_CREATEDBY", nullable = false, length = 32)
	public String getDatachangeCreatedby() {
		return this.datachangeCreatedby;
	}

	public void setDatachangeCreatedby(String datachangeCreatedby) {
		this.datachangeCreatedby = datachangeCreatedby;
	}

	@Column(name = "DATACHANGE_CREATEDTIME", length = 11)
	public Date getDatachangeCreatedtime() {
		return this.datachangeCreatedtime;
	}

	public void setDatachangeCreatedtime(Date datachangeCreatedtime) {
		this.datachangeCreatedtime = datachangeCreatedtime;
	}

	@Column(name = "DATACHANGE_LASTMODIFIEDBY", length = 32)
	public String getDatachangeLastmodifiedby() {
		return this.datachangeLastmodifiedby;
	}

	public void setDatachangeLastmodifiedby(String datachangeLastmodifiedby) {
		this.datachangeLastmodifiedby = datachangeLastmodifiedby;
	}

	@Column(name = "DATACHANGE_LASTTIME", length = 11)
	public Date getDatachangeLasttime() {
		return this.datachangeLasttime;
	}

	public void setDatachangeLasttime(Date datachangeLasttime) {
		this.datachangeLasttime = datachangeLasttime;
	}
}
