package com.demo.domain;
// Generated 2018-9-18 14:14:55 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cluster generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "cluster")
public class Cluster implements java.io.Serializable {
	private long id;
	private String name;
	private String appid;
	private long parentclusterid;
	private char isdeleted;
	private String datachangeCreatedby;
	private Date datachangeCreatedtime;
	private String datachangeLastmodifiedby;
	private Date datachangeLasttime;

	public Cluster() {
	}

	public Cluster(long id, String name, String appid, long parentclusterid, char isdeleted, String datachangeCreatedby,
			Date datachangeCreatedtime) {
		this.id = id;
		this.name = name;
		this.appid = appid;
		this.parentclusterid = parentclusterid;
		this.isdeleted = isdeleted;
		this.datachangeCreatedby = datachangeCreatedby;
		this.datachangeCreatedtime = datachangeCreatedtime;
	}

	public Cluster(long id, String name, String appid, long parentclusterid, char isdeleted, String datachangeCreatedby,
			Date datachangeCreatedtime, String datachangeLastmodifiedby, Date datachangeLasttime) {
		this.id = id;
		this.name = name;
		this.appid = appid;
		this.parentclusterid = parentclusterid;
		this.isdeleted = isdeleted;
		this.datachangeCreatedby = datachangeCreatedby;
		this.datachangeCreatedtime = datachangeCreatedtime;
		this.datachangeLastmodifiedby = datachangeLastmodifiedby;
		this.datachangeLasttime = datachangeLasttime;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "NAME", nullable = false, length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "APPID", nullable = false, length = 32)
	public String getAppid() {
		return this.appid;
	}

	public void setAppid(String appid) {
		this.appid = appid;
	}

	@Column(name = "PARENTCLUSTERID", nullable = false, precision = 10, scale = 0)
	public long getParentclusterid() {
		return this.parentclusterid;
	}

	public void setParentclusterid(long parentclusterid) {
		this.parentclusterid = parentclusterid;
	}

	@Column(name = "ISDELETED", nullable = false, length = 1)
	public char getIsdeleted() {
		return this.isdeleted;
	}

	public void setIsdeleted(char isdeleted) {
		this.isdeleted = isdeleted;
	}

	@Column(name = "DATACHANGE_CREATEDBY", nullable = false, length = 32)
	public String getDatachangeCreatedby() {
		return this.datachangeCreatedby;
	}

	public void setDatachangeCreatedby(String datachangeCreatedby) {
		this.datachangeCreatedby = datachangeCreatedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATACHANGE_CREATEDTIME", nullable = false, length = 11)
	public Date getDatachangeCreatedtime() {
		return this.datachangeCreatedtime;
	}

	public void setDatachangeCreatedtime(Date datachangeCreatedtime) {
		this.datachangeCreatedtime = datachangeCreatedtime;
	}

	@Column(name = "DATACHANGE_LASTMODIFIEDBY", length = 32)
	public String getDatachangeLastmodifiedby() {
		return this.datachangeLastmodifiedby;
	}

	public void setDatachangeLastmodifiedby(String datachangeLastmodifiedby) {
		this.datachangeLastmodifiedby = datachangeLastmodifiedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATACHANGE_LASTTIME", length = 11)
	public Date getDatachangeLasttime() {
		return this.datachangeLasttime;
	}

	public void setDatachangeLasttime(Date datachangeLasttime) {
		this.datachangeLasttime = datachangeLasttime;
	}
}
