package com.demo.domain;
// Generated 2018-9-18 14:14:55 by Hibernate Tools 5.2.11.Final

import java.sql.Clob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Commit generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "COMMIT")
public class Commit implements java.io.Serializable {
	private long id;
	private Clob changesets;
	private String appid;
	private String clustername;
	private String namespacename;
	private String comment;
	private Character isdeleted;
	private String datachangeCreatedby;
	private Date datachangeCreatedtime;
	private String datachangeLastmodifiedby;
	private Date datachangeLasttime;

	public Commit() {
	}

	public Commit(long id) {
		this.id = id;
	}

	public Commit(long id, Clob changesets, String appid, String clustername, String namespacename, String comment,
			Character isdeleted, String datachangeCreatedby, Date datachangeCreatedtime,
			String datachangeLastmodifiedby, Date datachangeLasttime) {
		this.id = id;
		this.changesets = changesets;
		this.appid = appid;
		this.clustername = clustername;
		this.namespacename = namespacename;
		this.comment = comment;
		this.isdeleted = isdeleted;
		this.datachangeCreatedby = datachangeCreatedby;
		this.datachangeCreatedtime = datachangeCreatedtime;
		this.datachangeLastmodifiedby = datachangeLastmodifiedby;
		this.datachangeLasttime = datachangeLasttime;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "CHANGESETS")
	public Clob getChangesets() {
		return this.changesets;
	}

	public void setChangesets(Clob changesets) {
		this.changesets = changesets;
	}

	@Column(name = "APPID", length = 500)
	public String getAppid() {
		return this.appid;
	}

	public void setAppid(String appid) {
		this.appid = appid;
	}

	@Column(name = "CLUSTERNAME", length = 500)
	public String getClustername() {
		return this.clustername;
	}

	public void setClustername(String clustername) {
		this.clustername = clustername;
	}

	@Column(name = "NAMESPACENAME", length = 500)
	public String getNamespacename() {
		return this.namespacename;
	}

	public void setNamespacename(String namespacename) {
		this.namespacename = namespacename;
	}

	@Column(name = "comment", length = 500)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "ISDELETED", length = 1)
	public Character getIsdeleted() {
		return this.isdeleted;
	}

	public void setIsdeleted(Character isdeleted) {
		this.isdeleted = isdeleted;
	}

	@Column(name = "DATACHANGE_CREATEDBY", length = 32)
	public String getDatachangeCreatedby() {
		return this.datachangeCreatedby;
	}

	public void setDatachangeCreatedby(String datachangeCreatedby) {
		this.datachangeCreatedby = datachangeCreatedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATACHANGE_CREATEDTIME", length = 11)
	public Date getDatachangeCreatedtime() {
		return this.datachangeCreatedtime;
	}

	public void setDatachangeCreatedtime(Date datachangeCreatedtime) {
		this.datachangeCreatedtime = datachangeCreatedtime;
	}

	@Column(name = "DATACHANGE_LASTMODIFIEDBY", length = 32)
	public String getDatachangeLastmodifiedby() {
		return this.datachangeLastmodifiedby;
	}

	public void setDatachangeLastmodifiedby(String datachangeLastmodifiedby) {
		this.datachangeLastmodifiedby = datachangeLastmodifiedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATACHANGE_LASTTIME", length = 11)
	public Date getDatachangeLasttime() {
		return this.datachangeLasttime;
	}

	public void setDatachangeLasttime(Date datachangeLasttime) {
		this.datachangeLasttime = datachangeLasttime;
	}
}
