package com.demo.domain;
// Generated 2018-9-18 14:14:55 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import org.hibernate.annotations.DynamicInsert;

/**
 * Commit generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "COMMIT")
@DynamicInsert
public class Commit implements java.io.Serializable {
	private long id;
	private String changesets;
	private String appid;
	private String clustername;
	private String namespacename;
	private String comment;
	private boolean isDeleted;
	private String datachangeCreatedby;
	private Date datachangeCreatedtime;
	private String datachangeLastmodifiedby;
	private Date datachangeLasttime;

	public Commit() {
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "COMMIT_SEQ")
	@SequenceGenerator(name = "COMMIT_SEQ", sequenceName = "COMMIT_SEQ", allocationSize = 1, initialValue = 1)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "CHANGESETS")
	public String getChangesets() {
		return this.changesets;
	}

	public void setChangesets(String changesets) {
		this.changesets = changesets;
	}

	@Column(name = "APPID", length = 500)
	public String getAppid() {
		return this.appid;
	}

	public void setAppid(String appid) {
		this.appid = appid;
	}

	@Column(name = "CLUSTERNAME", length = 500)
	public String getClustername() {
		return this.clustername;
	}

	public void setClustername(String clustername) {
		this.clustername = clustername;
	}

	@Column(name = "NAMESPACENAME", length = 500)
	public String getNamespacename() {
		return this.namespacename;
	}

	public void setNamespacename(String namespacename) {
		this.namespacename = namespacename;
	}

	@Column(name = "comment", length = 500)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "ISDELETED", length = 1)
	public boolean isDeleted() {
		return isDeleted;
	}

	public void setDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "DATACHANGE_CREATEDBY", length = 32)
	public String getDatachangeCreatedby() {
		return this.datachangeCreatedby;
	}

	public void setDatachangeCreatedby(String datachangeCreatedby) {
		this.datachangeCreatedby = datachangeCreatedby;
	}

	@Column(name = "DATACHANGE_CREATEDTIME", length = 11)
	public Date getDatachangeCreatedtime() {
		return this.datachangeCreatedtime;
	}

	public void setDatachangeCreatedtime(Date datachangeCreatedtime) {
		this.datachangeCreatedtime = datachangeCreatedtime;
	}

	@Column(name = "DATACHANGE_LASTMODIFIEDBY", length = 32)
	public String getDatachangeLastmodifiedby() {
		return this.datachangeLastmodifiedby;
	}

	public void setDatachangeLastmodifiedby(String datachangeLastmodifiedby) {
		this.datachangeLastmodifiedby = datachangeLastmodifiedby;
	}

	@Column(name = "DATACHANGE_LASTTIME", length = 11)
	public Date getDatachangeLasttime() {
		return this.datachangeLasttime;
	}

	public void setDatachangeLasttime(Date datachangeLasttime) {
		this.datachangeLasttime = datachangeLasttime;
	}
}
