package com.demo.domain;
// Generated 2018-9-18 14:14:55 by Hibernate Tools 5.2.11.Final

import java.sql.Clob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Grayreleaserule generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "GRAYRELEASERULE")
public class Grayreleaserule implements java.io.Serializable {
	private long id;
	private String appid;
	private String clustername;
	private String namespacename;
	private String branchname;
	private Clob rules;
	private long releaseid;
	private Byte branchstatus;
	private char isdeleted;
	private String datachangeCreatedby;
	private Date datachangeCreatedtime;
	private String datachangeLastmodifiedby;
	private Date datachangeLasttime;

	public Grayreleaserule() {
	}

	public Grayreleaserule(long id, String appid, String clustername, String namespacename, String branchname,
			long releaseid, char isdeleted, String datachangeCreatedby, Date datachangeCreatedtime) {
		this.id = id;
		this.appid = appid;
		this.clustername = clustername;
		this.namespacename = namespacename;
		this.branchname = branchname;
		this.releaseid = releaseid;
		this.isdeleted = isdeleted;
		this.datachangeCreatedby = datachangeCreatedby;
		this.datachangeCreatedtime = datachangeCreatedtime;
	}

	public Grayreleaserule(long id, String appid, String clustername, String namespacename, String branchname,
			Clob rules, long releaseid, Byte branchstatus, char isdeleted, String datachangeCreatedby,
			Date datachangeCreatedtime, String datachangeLastmodifiedby, Date datachangeLasttime) {
		this.id = id;
		this.appid = appid;
		this.clustername = clustername;
		this.namespacename = namespacename;
		this.branchname = branchname;
		this.rules = rules;
		this.releaseid = releaseid;
		this.branchstatus = branchstatus;
		this.isdeleted = isdeleted;
		this.datachangeCreatedby = datachangeCreatedby;
		this.datachangeCreatedtime = datachangeCreatedtime;
		this.datachangeLastmodifiedby = datachangeLastmodifiedby;
		this.datachangeLasttime = datachangeLasttime;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 11, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "APPID", nullable = false, length = 32)
	public String getAppid() {
		return this.appid;
	}

	public void setAppid(String appid) {
		this.appid = appid;
	}

	@Column(name = "CLUSTERNAME", nullable = false, length = 32)
	public String getClustername() {
		return this.clustername;
	}

	public void setClustername(String clustername) {
		this.clustername = clustername;
	}

	@Column(name = "NAMESPACENAME", nullable = false, length = 32)
	public String getNamespacename() {
		return this.namespacename;
	}

	public void setNamespacename(String namespacename) {
		this.namespacename = namespacename;
	}

	@Column(name = "BRANCHNAME", nullable = false, length = 32)
	public String getBranchname() {
		return this.branchname;
	}

	public void setBranchname(String branchname) {
		this.branchname = branchname;
	}

	@Column(name = "RULES")
	public Clob getRules() {
		return this.rules;
	}

	public void setRules(Clob rules) {
		this.rules = rules;
	}

	@Column(name = "RELEASEID", nullable = false, precision = 11, scale = 0)
	public long getReleaseid() {
		return this.releaseid;
	}

	public void setReleaseid(long releaseid) {
		this.releaseid = releaseid;
	}

	@Column(name = "BRANCHSTATUS", precision = 2, scale = 0)
	public Byte getBranchstatus() {
		return this.branchstatus;
	}

	public void setBranchstatus(Byte branchstatus) {
		this.branchstatus = branchstatus;
	}

	@Column(name = "ISDELETED", nullable = false, length = 1)
	public char getIsdeleted() {
		return this.isdeleted;
	}

	public void setIsdeleted(char isdeleted) {
		this.isdeleted = isdeleted;
	}

	@Column(name = "DATACHANGE_CREATEDBY", nullable = false, length = 32)
	public String getDatachangeCreatedby() {
		return this.datachangeCreatedby;
	}

	public void setDatachangeCreatedby(String datachangeCreatedby) {
		this.datachangeCreatedby = datachangeCreatedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATACHANGE_CREATEDTIME", nullable = false, length = 11)
	public Date getDatachangeCreatedtime() {
		return this.datachangeCreatedtime;
	}

	public void setDatachangeCreatedtime(Date datachangeCreatedtime) {
		this.datachangeCreatedtime = datachangeCreatedtime;
	}

	@Column(name = "DATACHANGE_LASTMODIFIEDBY", length = 32)
	public String getDatachangeLastmodifiedby() {
		return this.datachangeLastmodifiedby;
	}

	public void setDatachangeLastmodifiedby(String datachangeLastmodifiedby) {
		this.datachangeLastmodifiedby = datachangeLastmodifiedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATACHANGE_LASTTIME", length = 11)
	public Date getDatachangeLasttime() {
		return this.datachangeLasttime;
	}

	public void setDatachangeLasttime(Date datachangeLasttime) {
		this.datachangeLasttime = datachangeLasttime;
	}
}
