package com.demo.domain;
// Generated 2018-9-18 14:14:55 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Instanceconfig generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "INSTANCECONFIG", uniqueConstraints = @UniqueConstraint(columnNames = { "INSTANCEID", "CONFIGAPPID",
		"CONFIGNAMESPACENAME" }))
public class Instanceconfig implements java.io.Serializable {
	private long id;
	private Long instanceid;
	private String configappid;
	private String configclustername;
	private String confignamespacename;
	private String releasekey;
	private Date releasedeliverytime;
	private Date datachangeCreatedtime;
	private Date datachangeLasttime;

	public Instanceconfig() {
	}

	public Instanceconfig(long id, String configappid, String configclustername, String confignamespacename,
			String releasekey, Date datachangeCreatedtime, Date datachangeLasttime) {
		this.id = id;
		this.configappid = configappid;
		this.configclustername = configclustername;
		this.confignamespacename = confignamespacename;
		this.releasekey = releasekey;
		this.datachangeCreatedtime = datachangeCreatedtime;
		this.datachangeLasttime = datachangeLasttime;
	}

	public Instanceconfig(long id, Long instanceid, String configappid, String configclustername,
			String confignamespacename, String releasekey, Date releasedeliverytime, Date datachangeCreatedtime,
			Date datachangeLasttime) {
		this.id = id;
		this.instanceid = instanceid;
		this.configappid = configappid;
		this.configclustername = configclustername;
		this.confignamespacename = confignamespacename;
		this.releasekey = releasekey;
		this.releasedeliverytime = releasedeliverytime;
		this.datachangeCreatedtime = datachangeCreatedtime;
		this.datachangeLasttime = datachangeLasttime;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 11, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "INSTANCEID", precision = 11, scale = 0)
	public Long getInstanceid() {
		return this.instanceid;
	}

	public void setInstanceid(Long instanceid) {
		this.instanceid = instanceid;
	}

	@Column(name = "CONFIGAPPID", nullable = false, length = 32)
	public String getConfigappid() {
		return this.configappid;
	}

	public void setConfigappid(String configappid) {
		this.configappid = configappid;
	}

	@Column(name = "CONFIGCLUSTERNAME", nullable = false, length = 32)
	public String getConfigclustername() {
		return this.configclustername;
	}

	public void setConfigclustername(String configclustername) {
		this.configclustername = configclustername;
	}

	@Column(name = "CONFIGNAMESPACENAME", nullable = false, length = 32)
	public String getConfignamespacename() {
		return this.confignamespacename;
	}

	public void setConfignamespacename(String confignamespacename) {
		this.confignamespacename = confignamespacename;
	}

	@Column(name = "RELEASEKEY", nullable = false, length = 64)
	public String getReleasekey() {
		return this.releasekey;
	}

	public void setReleasekey(String releasekey) {
		this.releasekey = releasekey;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RELEASEDELIVERYTIME", length = 11)
	public Date getReleasedeliverytime() {
		return this.releasedeliverytime;
	}

	public void setReleasedeliverytime(Date releasedeliverytime) {
		this.releasedeliverytime = releasedeliverytime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATACHANGE_CREATEDTIME", nullable = false, length = 11)
	public Date getDatachangeCreatedtime() {
		return this.datachangeCreatedtime;
	}

	public void setDatachangeCreatedtime(Date datachangeCreatedtime) {
		this.datachangeCreatedtime = datachangeCreatedtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATACHANGE_LASTTIME", nullable = false, length = 11)
	public Date getDatachangeLasttime() {
		return this.datachangeLasttime;
	}

	public void setDatachangeLasttime(Date datachangeLasttime) {
		this.datachangeLasttime = datachangeLasttime;
	}
}
