package com.demo.domain;
// Generated 2018-9-18 14:14:55 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Instance generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "INSTANCE", uniqueConstraints = @UniqueConstraint(columnNames = { "APPID", "CLUSTERNAME", "IP",
		"DATACENTER" }))
public class Instance implements java.io.Serializable {
	private long id;
	private String appid;
	private String clustername;
	private String datacenter;
	private String ip;
	private Date datachangeCreatedtime;
	private Date datachangeLasttime;

	public Instance() {
	}

	public Instance(long id, String appid, String clustername, String datacenter, String ip, Date datachangeCreatedtime,
			Date datachangeLasttime) {
		this.id = id;
		this.appid = appid;
		this.clustername = clustername;
		this.datacenter = datacenter;
		this.ip = ip;
		this.datachangeCreatedtime = datachangeCreatedtime;
		this.datachangeLasttime = datachangeLasttime;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 11, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "APPID", nullable = false, length = 32)
	public String getAppid() {
		return this.appid;
	}

	public void setAppid(String appid) {
		this.appid = appid;
	}

	@Column(name = "CLUSTERNAME", nullable = false, length = 32)
	public String getClustername() {
		return this.clustername;
	}

	public void setClustername(String clustername) {
		this.clustername = clustername;
	}

	@Column(name = "DATACENTER", nullable = false, length = 64)
	public String getDatacenter() {
		return this.datacenter;
	}

	public void setDatacenter(String datacenter) {
		this.datacenter = datacenter;
	}

	@Column(name = "IP", nullable = false, length = 32)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATACHANGE_CREATEDTIME", nullable = false, length = 11)
	public Date getDatachangeCreatedtime() {
		return this.datachangeCreatedtime;
	}

	public void setDatachangeCreatedtime(Date datachangeCreatedtime) {
		this.datachangeCreatedtime = datachangeCreatedtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATACHANGE_LASTTIME", nullable = false, length = 11)
	public Date getDatachangeLasttime() {
		return this.datachangeLasttime;
	}

	public void setDatachangeLasttime(Date datachangeLasttime) {
		this.datachangeLasttime = datachangeLasttime;
	}
}
