package com.demo.domain;
// Generated 2018-9-18 14:14:55 by Hibernate Tools 5.2.11.Final

import java.sql.Clob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Item generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "ITEM")
public class Item implements java.io.Serializable {
	private long id;
	private long namespaceid;
	private String key;
	private Clob value;
	private String comment;
	private Long linenum;
	private char isdeleted;
	private String datachangeCreatedby;
	private Date datachangeCreatedtime;
	private String datachangeLastmodifiedby;
	private Date datachangeLasttime;

	public Item() {
	}

	public Item(long id, long namespaceid, String key, Clob value, char isdeleted, String datachangeCreatedby,
			Date datachangeCreatedtime) {
		this.id = id;
		this.namespaceid = namespaceid;
		this.key = key;
		this.value = value;
		this.isdeleted = isdeleted;
		this.datachangeCreatedby = datachangeCreatedby;
		this.datachangeCreatedtime = datachangeCreatedtime;
	}

	public Item(long id, long namespaceid, String key, Clob value, String comment, Long linenum, char isdeleted,
			String datachangeCreatedby, Date datachangeCreatedtime, String datachangeLastmodifiedby,
			Date datachangeLasttime) {
		this.id = id;
		this.namespaceid = namespaceid;
		this.key = key;
		this.value = value;
		this.comment = comment;
		this.linenum = linenum;
		this.isdeleted = isdeleted;
		this.datachangeCreatedby = datachangeCreatedby;
		this.datachangeCreatedtime = datachangeCreatedtime;
		this.datachangeLastmodifiedby = datachangeLastmodifiedby;
		this.datachangeLasttime = datachangeLasttime;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "NAMESPACEID", nullable = false, precision = 10, scale = 0)
	public long getNamespaceid() {
		return this.namespaceid;
	}

	public void setNamespaceid(long namespaceid) {
		this.namespaceid = namespaceid;
	}

	@Column(name = "KEY", nullable = false, length = 128)
	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	@Column(name = "VALUE", nullable = false)
	public Clob getValue() {
		return this.value;
	}

	public void setValue(Clob value) {
		this.value = value;
	}

	@Column(name = "comment", length = 1024)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "LINENUM", precision = 10, scale = 0)
	public Long getLinenum() {
		return this.linenum;
	}

	public void setLinenum(Long linenum) {
		this.linenum = linenum;
	}

	@Column(name = "ISDELETED", nullable = false, length = 1)
	public char getIsdeleted() {
		return this.isdeleted;
	}

	public void setIsdeleted(char isdeleted) {
		this.isdeleted = isdeleted;
	}

	@Column(name = "DATACHANGE_CREATEDBY", nullable = false, length = 32)
	public String getDatachangeCreatedby() {
		return this.datachangeCreatedby;
	}

	public void setDatachangeCreatedby(String datachangeCreatedby) {
		this.datachangeCreatedby = datachangeCreatedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATACHANGE_CREATEDTIME", nullable = false, length = 11)
	public Date getDatachangeCreatedtime() {
		return this.datachangeCreatedtime;
	}

	public void setDatachangeCreatedtime(Date datachangeCreatedtime) {
		this.datachangeCreatedtime = datachangeCreatedtime;
	}

	@Column(name = "DATACHANGE_LASTMODIFIEDBY", length = 32)
	public String getDatachangeLastmodifiedby() {
		return this.datachangeLastmodifiedby;
	}

	public void setDatachangeLastmodifiedby(String datachangeLastmodifiedby) {
		this.datachangeLastmodifiedby = datachangeLastmodifiedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATACHANGE_LASTTIME", length = 11)
	public Date getDatachangeLasttime() {
		return this.datachangeLasttime;
	}

	public void setDatachangeLasttime(Date datachangeLasttime) {
		this.datachangeLasttime = datachangeLasttime;
	}
}
