package com.demo.domain;
// Generated 2018-9-18 14:14:55 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Namespacelock generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "NAMESPACELOCK", uniqueConstraints = @UniqueConstraint(columnNames = "NAMESPACEID"))
public class Namespacelock implements java.io.Serializable {
	private long id;
	private long namespaceid;
	private String datachangeCreatedby;
	private Date datachangeCreatedtime;
	private String datachangeLastmodifiedby;
	private Date datachangeLasttime;
	private Character isdeleted;

	public Namespacelock() {
	}

	public Namespacelock(long id, long namespaceid, String datachangeCreatedby, Date datachangeCreatedtime) {
		this.id = id;
		this.namespaceid = namespaceid;
		this.datachangeCreatedby = datachangeCreatedby;
		this.datachangeCreatedtime = datachangeCreatedtime;
	}

	public Namespacelock(long id, long namespaceid, String datachangeCreatedby, Date datachangeCreatedtime,
			String datachangeLastmodifiedby, Date datachangeLasttime, Character isdeleted) {
		this.id = id;
		this.namespaceid = namespaceid;
		this.datachangeCreatedby = datachangeCreatedby;
		this.datachangeCreatedtime = datachangeCreatedtime;
		this.datachangeLastmodifiedby = datachangeLastmodifiedby;
		this.datachangeLasttime = datachangeLasttime;
		this.isdeleted = isdeleted;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 11, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "NAMESPACEID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getNamespaceid() {
		return this.namespaceid;
	}

	public void setNamespaceid(long namespaceid) {
		this.namespaceid = namespaceid;
	}

	@Column(name = "DATACHANGE_CREATEDBY", nullable = false, length = 32)
	public String getDatachangeCreatedby() {
		return this.datachangeCreatedby;
	}

	public void setDatachangeCreatedby(String datachangeCreatedby) {
		this.datachangeCreatedby = datachangeCreatedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATACHANGE_CREATEDTIME", nullable = false, length = 11)
	public Date getDatachangeCreatedtime() {
		return this.datachangeCreatedtime;
	}

	public void setDatachangeCreatedtime(Date datachangeCreatedtime) {
		this.datachangeCreatedtime = datachangeCreatedtime;
	}

	@Column(name = "DATACHANGE_LASTMODIFIEDBY", length = 32)
	public String getDatachangeLastmodifiedby() {
		return this.datachangeLastmodifiedby;
	}

	public void setDatachangeLastmodifiedby(String datachangeLastmodifiedby) {
		this.datachangeLastmodifiedby = datachangeLastmodifiedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATACHANGE_LASTTIME", length = 11)
	public Date getDatachangeLasttime() {
		return this.datachangeLasttime;
	}

	public void setDatachangeLasttime(Date datachangeLasttime) {
		this.datachangeLasttime = datachangeLasttime;
	}

	@Column(name = "ISDELETED", length = 1)
	public Character getIsdeleted() {
		return this.isdeleted;
	}

	public void setIsdeleted(Character isdeleted) {
		this.isdeleted = isdeleted;
	}
}
