package com.demo.domain;
// Generated 2018-9-18 14:14:55 by Hibernate Tools 5.2.11.Final

import java.sql.Clob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Release generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "RELEASE")
public class Release implements java.io.Serializable {
	private long id;
	private String releasekey;
	private String name;
	private String comment;
	private String appid;
	private String clustername;
	private String namespacename;
	private Clob configurations;
	private Character isabandoned;
	private Character isdeleted;
	private String datachangeCreatedby;
	private Date datachangeCreatedtime;
	private String datachangeLastmodifiedby;
	private Date datachangeLasttime;

	public Release() {
	}

	public Release(long id) {
		this.id = id;
	}

	public Release(long id, String releasekey, String name, String comment, String appid, String clustername,
			String namespacename, Clob configurations, Character isabandoned, Character isdeleted,
			String datachangeCreatedby, Date datachangeCreatedtime, String datachangeLastmodifiedby,
			Date datachangeLasttime) {
		this.id = id;
		this.releasekey = releasekey;
		this.name = name;
		this.comment = comment;
		this.appid = appid;
		this.clustername = clustername;
		this.namespacename = namespacename;
		this.configurations = configurations;
		this.isabandoned = isabandoned;
		this.isdeleted = isdeleted;
		this.datachangeCreatedby = datachangeCreatedby;
		this.datachangeCreatedtime = datachangeCreatedtime;
		this.datachangeLastmodifiedby = datachangeLastmodifiedby;
		this.datachangeLasttime = datachangeLasttime;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "RELEASEKEY", length = 64)
	public String getReleasekey() {
		return this.releasekey;
	}

	public void setReleasekey(String releasekey) {
		this.releasekey = releasekey;
	}

	@Column(name = "NAME", length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "comment", length = 256)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "APPID", length = 500)
	public String getAppid() {
		return this.appid;
	}

	public void setAppid(String appid) {
		this.appid = appid;
	}

	@Column(name = "CLUSTERNAME", length = 500)
	public String getClustername() {
		return this.clustername;
	}

	public void setClustername(String clustername) {
		this.clustername = clustername;
	}

	@Column(name = "NAMESPACENAME", length = 500)
	public String getNamespacename() {
		return this.namespacename;
	}

	public void setNamespacename(String namespacename) {
		this.namespacename = namespacename;
	}

	@Column(name = "CONFIGURATIONS")
	public Clob getConfigurations() {
		return this.configurations;
	}

	public void setConfigurations(Clob configurations) {
		this.configurations = configurations;
	}

	@Column(name = "ISABANDONED", length = 1)
	public Character getIsabandoned() {
		return this.isabandoned;
	}

	public void setIsabandoned(Character isabandoned) {
		this.isabandoned = isabandoned;
	}

	@Column(name = "ISDELETED", length = 1)
	public Character getIsdeleted() {
		return this.isdeleted;
	}

	public void setIsdeleted(Character isdeleted) {
		this.isdeleted = isdeleted;
	}

	@Column(name = "DATACHANGE_CREATEDBY", length = 32)
	public String getDatachangeCreatedby() {
		return this.datachangeCreatedby;
	}

	public void setDatachangeCreatedby(String datachangeCreatedby) {
		this.datachangeCreatedby = datachangeCreatedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATACHANGE_CREATEDTIME", length = 11)
	public Date getDatachangeCreatedtime() {
		return this.datachangeCreatedtime;
	}

	public void setDatachangeCreatedtime(Date datachangeCreatedtime) {
		this.datachangeCreatedtime = datachangeCreatedtime;
	}

	@Column(name = "DATACHANGE_LASTMODIFIEDBY", length = 32)
	public String getDatachangeLastmodifiedby() {
		return this.datachangeLastmodifiedby;
	}

	public void setDatachangeLastmodifiedby(String datachangeLastmodifiedby) {
		this.datachangeLastmodifiedby = datachangeLastmodifiedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATACHANGE_LASTTIME", length = 11)
	public Date getDatachangeLasttime() {
		return this.datachangeLasttime;
	}

	public void setDatachangeLasttime(Date datachangeLasttime) {
		this.datachangeLasttime = datachangeLasttime;
	}
}
