package com.demo.domain;
// Generated 2018-9-18 14:14:55 by Hibernate Tools 5.2.11.Final

import java.sql.Clob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Releasehistory generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "RELEASEHISTORY")
public class Releasehistory implements java.io.Serializable {
	private long id;
	private String appid;
	private String clustername;
	private String namespacename;
	private String branchname;
	private Long releaseid;
	private Long previousreleaseid;
	private Short operation;
	private Clob operationcontext;
	private Character isdeleted;
	private String datachangeCreatedby;
	private Date datachangeCreatedtime;
	private String datachangeLastmodifiedby;
	private Date datachangeLasttime;

	public Releasehistory() {
	}

	public Releasehistory(long id) {
		this.id = id;
	}

	public Releasehistory(long id, String appid, String clustername, String namespacename, String branchname,
			Long releaseid, Long previousreleaseid, Short operation, Clob operationcontext, Character isdeleted,
			String datachangeCreatedby, Date datachangeCreatedtime, String datachangeLastmodifiedby,
			Date datachangeLasttime) {
		this.id = id;
		this.appid = appid;
		this.clustername = clustername;
		this.namespacename = namespacename;
		this.branchname = branchname;
		this.releaseid = releaseid;
		this.previousreleaseid = previousreleaseid;
		this.operation = operation;
		this.operationcontext = operationcontext;
		this.isdeleted = isdeleted;
		this.datachangeCreatedby = datachangeCreatedby;
		this.datachangeCreatedtime = datachangeCreatedtime;
		this.datachangeLastmodifiedby = datachangeLastmodifiedby;
		this.datachangeLasttime = datachangeLasttime;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 11, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "APPID", length = 32)
	public String getAppid() {
		return this.appid;
	}

	public void setAppid(String appid) {
		this.appid = appid;
	}

	@Column(name = "CLUSTERNAME", length = 32)
	public String getClustername() {
		return this.clustername;
	}

	public void setClustername(String clustername) {
		this.clustername = clustername;
	}

	@Column(name = "NAMESPACENAME", length = 32)
	public String getNamespacename() {
		return this.namespacename;
	}

	public void setNamespacename(String namespacename) {
		this.namespacename = namespacename;
	}

	@Column(name = "BRANCHNAME", length = 32)
	public String getBranchname() {
		return this.branchname;
	}

	public void setBranchname(String branchname) {
		this.branchname = branchname;
	}

	@Column(name = "RELEASEID", precision = 11, scale = 0)
	public Long getReleaseid() {
		return this.releaseid;
	}

	public void setReleaseid(Long releaseid) {
		this.releaseid = releaseid;
	}

	@Column(name = "PREVIOUSRELEASEID", precision = 11, scale = 0)
	public Long getPreviousreleaseid() {
		return this.previousreleaseid;
	}

	public void setPreviousreleaseid(Long previousreleaseid) {
		this.previousreleaseid = previousreleaseid;
	}

	@Column(name = "OPERATION", precision = 3, scale = 0)
	public Short getOperation() {
		return this.operation;
	}

	public void setOperation(Short operation) {
		this.operation = operation;
	}

	@Column(name = "OPERATIONCONTEXT")
	public Clob getOperationcontext() {
		return this.operationcontext;
	}

	public void setOperationcontext(Clob operationcontext) {
		this.operationcontext = operationcontext;
	}

	@Column(name = "ISDELETED", length = 1)
	public Character getIsdeleted() {
		return this.isdeleted;
	}

	public void setIsdeleted(Character isdeleted) {
		this.isdeleted = isdeleted;
	}

	@Column(name = "DATACHANGE_CREATEDBY", length = 32)
	public String getDatachangeCreatedby() {
		return this.datachangeCreatedby;
	}

	public void setDatachangeCreatedby(String datachangeCreatedby) {
		this.datachangeCreatedby = datachangeCreatedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATACHANGE_CREATEDTIME", length = 11)
	public Date getDatachangeCreatedtime() {
		return this.datachangeCreatedtime;
	}

	public void setDatachangeCreatedtime(Date datachangeCreatedtime) {
		this.datachangeCreatedtime = datachangeCreatedtime;
	}

	@Column(name = "DATACHANGE_LASTMODIFIEDBY", length = 32)
	public String getDatachangeLastmodifiedby() {
		return this.datachangeLastmodifiedby;
	}

	public void setDatachangeLastmodifiedby(String datachangeLastmodifiedby) {
		this.datachangeLastmodifiedby = datachangeLastmodifiedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATACHANGE_LASTTIME", length = 11)
	public Date getDatachangeLasttime() {
		return this.datachangeLasttime;
	}

	public void setDatachangeLasttime(Date datachangeLasttime) {
		this.datachangeLasttime = datachangeLasttime;
	}
}
