package com.demo.domain;
// Generated 2018-9-18 14:14:55 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Serverconfig generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "SERVERCONFIG")
public class Serverconfig implements java.io.Serializable {
	private long id;
	private String key;
	private String cluster;
	private String value;
	private String comment;
	private char isdeleted;
	private String datachangeCreatedby;
	private Date datachangeCreatedtime;
	private String datachangeLastmodifiedby;
	private Date datachangeLasttime;

	public Serverconfig() {
	}

	public Serverconfig(long id, String key, String cluster, String value, char isdeleted, String datachangeCreatedby,
			Date datachangeCreatedtime) {
		this.id = id;
		this.key = key;
		this.cluster = cluster;
		this.value = value;
		this.isdeleted = isdeleted;
		this.datachangeCreatedby = datachangeCreatedby;
		this.datachangeCreatedtime = datachangeCreatedtime;
	}

	public Serverconfig(long id, String key, String cluster, String value, String comment, char isdeleted,
			String datachangeCreatedby, Date datachangeCreatedtime, String datachangeLastmodifiedby,
			Date datachangeLasttime) {
		this.id = id;
		this.key = key;
		this.cluster = cluster;
		this.value = value;
		this.comment = comment;
		this.isdeleted = isdeleted;
		this.datachangeCreatedby = datachangeCreatedby;
		this.datachangeCreatedtime = datachangeCreatedtime;
		this.datachangeLastmodifiedby = datachangeLastmodifiedby;
		this.datachangeLasttime = datachangeLasttime;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "KEY", nullable = false, length = 64)
	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	@Column(name = "cluster", nullable = false, length = 32)
	public String getCluster() {
		return this.cluster;
	}

	public void setCluster(String cluster) {
		this.cluster = cluster;
	}

	@Column(name = "VALUE", nullable = false, length = 2048)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "comment", length = 1024)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "ISDELETED", nullable = false, length = 1)
	public char getIsdeleted() {
		return this.isdeleted;
	}

	public void setIsdeleted(char isdeleted) {
		this.isdeleted = isdeleted;
	}

	@Column(name = "DATACHANGE_CREATEDBY", nullable = false, length = 32)
	public String getDatachangeCreatedby() {
		return this.datachangeCreatedby;
	}

	public void setDatachangeCreatedby(String datachangeCreatedby) {
		this.datachangeCreatedby = datachangeCreatedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATACHANGE_CREATEDTIME", nullable = false, length = 11)
	public Date getDatachangeCreatedtime() {
		return this.datachangeCreatedtime;
	}

	public void setDatachangeCreatedtime(Date datachangeCreatedtime) {
		this.datachangeCreatedtime = datachangeCreatedtime;
	}

	@Column(name = "DATACHANGE_LASTMODIFIEDBY", length = 32)
	public String getDatachangeLastmodifiedby() {
		return this.datachangeLastmodifiedby;
	}

	public void setDatachangeLastmodifiedby(String datachangeLastmodifiedby) {
		this.datachangeLastmodifiedby = datachangeLastmodifiedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATACHANGE_LASTTIME", length = 11)
	public Date getDatachangeLasttime() {
		return this.datachangeLasttime;
	}

	public void setDatachangeLasttime(Date datachangeLasttime) {
		this.datachangeLasttime = datachangeLasttime;
	}
}
