package com.demo.domain;
// Generated 2018-9-18 14:14:55 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import org.hibernate.annotations.DynamicInsert;

/**
 * Serverconfig generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "SERVERCONFIG")
@DynamicInsert
public class Serverconfig implements java.io.Serializable {
	private long id;
	private String key;
	private String cluster;
	private String value;
	private String comment;
	private boolean isDeleted;
	private String datachangeCreatedby;
	private Date datachangeCreatedtime;
	private String datachangeLastmodifiedby;
	private Date datachangeLasttime;

	public Serverconfig() {
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SERVERCONFIG_SEQ")
	@SequenceGenerator(name = "SERVERCONFIG_SEQ", sequenceName = "SERVERCONFIG_SEQ", allocationSize = 1, initialValue = 1)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "KEY", nullable = false, length = 64)
	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	@Column(name = "cluster", nullable = false, length = 32)
	public String getCluster() {
		return this.cluster;
	}

	public void setCluster(String cluster) {
		this.cluster = cluster;
	}

	@Column(name = "VALUE", nullable = false, length = 2048)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "comment", length = 1024)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "ISDELETED", nullable = false, length = 1)
	public boolean isDeleted() {
		return isDeleted;
	}

	public void setDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "DATACHANGE_CREATEDBY", nullable = false, length = 32)
	public String getDatachangeCreatedby() {
		return this.datachangeCreatedby;
	}

	public void setDatachangeCreatedby(String datachangeCreatedby) {
		this.datachangeCreatedby = datachangeCreatedby;
	}

	@Column(name = "DATACHANGE_CREATEDTIME", length = 11)
	public Date getDatachangeCreatedtime() {
		return this.datachangeCreatedtime;
	}

	public void setDatachangeCreatedtime(Date datachangeCreatedtime) {
		this.datachangeCreatedtime = datachangeCreatedtime;
	}

	@Column(name = "DATACHANGE_LASTMODIFIEDBY", length = 32)
	public String getDatachangeLastmodifiedby() {
		return this.datachangeLastmodifiedby;
	}

	public void setDatachangeLastmodifiedby(String datachangeLastmodifiedby) {
		this.datachangeLastmodifiedby = datachangeLastmodifiedby;
	}

	@Column(name = "DATACHANGE_LASTTIME", length = 11)
	public Date getDatachangeLasttime() {
		return this.datachangeLasttime;
	}

	public void setDatachangeLasttime(Date datachangeLasttime) {
		this.datachangeLasttime = datachangeLasttime;
	}
}
