server:
  port: 8081
  servlet:
    context-path: /spring
    jsp:
      registered: false
  ssl:
    enabled: false

spring:
  aop:
    auto: false
  dao:
    exceptiontranslation:
      enabled: false
  jackson:
    locale: zh_CN
    time-zone: GMT+8
  mvc:
    publish-request-handled-events: false
  servlet:
    multipart:
      enabled: false
  thymeleaf:
    cache: false
    check-template: false
    check-template-location: false
  messages:
    basename: org.springframework.security.messages,com.example.security.messages
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai
  sql:
    init:
      mode: never
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: never
      table-name: T_USER_SESSION
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.task.TaskExecutionAutoConfiguration
    - org.springframework.boot.autoconfigure.task.TaskSchedulingAutoConfiguration
    - org.springframework.boot.autoconfigure.info.ProjectInfoAutoConfiguration
    - org.springframework.boot.autoconfigure.validation.ValidationAutoConfiguration
    - org.springframework.boot.autoconfigure.aop.AopAutoConfiguration
    - org.springframework.boot.autoconfigure.web.servlet.MultipartAutoConfiguration
    - org.springframework.boot.autoconfigure.dao.PersistenceExceptionTranslationAutoConfiguration
    - org.springframework.boot.autoconfigure.web.client.RestTemplateAutoConfiguration
    - org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration
    - org.springframework.boot.autoconfigure.websocket.servlet.WebSocketServletAutoConfiguration
    - org.springframework.boot.autoconfigure.data.web.SpringDataWebAutoConfiguration

kaptcha:
  image:
    width: 150
    height: 50
  textproducer:
    char-string: 0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
    char-length: 4
