server:
  port: 8082

spring:
  application:
    name: nacos-provider
  boot:
    admin:
      client:
        url: http://localhost:8080
        username: admin
        password: admin@2022

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
