server:
  port: 8080

spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      server-addr: 192.168.34.156:8848
      username: nacos
      password: nacos
      config:
        context-path: /nacos
        namespace: 
        file-extension: yml
      discovery:
        namespace: public

