server:
  servlet:
    context-path: /app
  port: 8088
  ssl:
    key-store: classpath:tomcat.ks
    key-store-password: springboot

spring:
  application:
    name: spring-security-rest-api

api:
  auth:
    header-name: X-API-KEY
    header-value: hello

