server:
  port: 8081
  ssl:
    enabled: false
  servlet:
    jsp:
      registered: false
    encoding:
      force: true
      force-request: true
      force-response: true
  compression:
    enabled: true

spring:
  application:
    name: swagger-knife4j
    admin:
      enabled: false
  jmx:
    enabled: false

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
    groups:
      enabled: true
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.example.demo.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
