spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: enc(F5qYZDfOeGE26wHjxxcAqnxIaXVper1E)
    initialization-mode: never
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.info.ProjectInfoAutoConfiguration
    - org.springframework.boot.autoconfigure.dao.PersistenceExceptionTranslationAutoConfiguration
    - org.springframework.boot.autoconfigure.aop.AopAutoConfiguration

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: helloworld
    property:
      prefix: enc(
      suffix: )
