server:
#  port: 8888
  servlet:
#    context-path: /
    jsp:
      registered: false
  ssl:
    enabled: false
spring:
  aop:
    auto: false
  dao:
    exceptiontranslation:
      enabled: false
  jackson:
    locale: zh_CN
    time-zone: GMT+8
  ldap:
    #LDAP连接
    urls: ldap://10.2.1.114:389
    #LDAP节点
    base: dc=bacic5i5j,dc=com
    #LDAP用户名
    username: cn=admin,dc=bacic5i5j,dc=com
    #LDAP密码
    password: 1q2w3e4r
  mail:
    #SMTP邮箱地址
    host: smtp.exmail.qq.com
    #SMTP邮箱端口（建议使用安全协议的端口号）
    port: 465
    #SMTP邮箱用户名
    username: siqianwen@5i5j.com
    #SMTP邮箱密码
    password: DcAfBAJsxCvAt6NA
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  main:
    allow-bean-definition-overriding: true
  mvc:
    publish-request-handled-events: false
  servlet:
    multipart:
      enabled: false
  thymeleaf:
#    cache: false
    check-template: false
    check-template-location: false
changepwd:
    #重置密码
    reset:
      #链接有效期（单位：分钟）
      expiration: 5
      #发件人（${}是占位符，请谨慎修改）
      from: 配置中心密码重置（涉及SVN、GIT、JIRA、WIKI）<${spring.mail.username}>
      #邮件主题
      subject: 重置您的密码
      #邮件内容（%s是占位符，请谨慎修改）
      text: '%s 您好，<br><br>点击以下链接重置您的密码，该链接${changepwd.reset.expiration}分钟后失效：<br><br><a href="%s" target="_blank">%s</a><br><br>如果您没有请求修改密码，请忽略该邮件。'
    #修改密码
    update:
      #发件人（${}是占位符，请谨慎修改）
      from: 配置中心密码重置（涉及SVN、GIT、JIRA、WIKI）<${spring.mail.username}>
      #邮件主题
      subject: 您的密码已修改
      #邮件内容（%s是占位符，请谨慎修改）
      text: '%s 您好，<br><br>您的密码已修改。<br><br>如果您没有修改密码，请立即联系您的管理员。'