server:
  port: 8080
  servlet:
    jsp:
      registered: false
spring:
  aop:
    auto: false
  sql:
    init:
      mode: never
  servlet:
    multipart:
      enabled: false
  main:
    web-application-type: servlet
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.task.TaskExecutionAutoConfiguration
    - org.springframework.boot.autoconfigure.info.ProjectInfoAutoConfiguration
    - org.springframework.boot.autoconfigure.task.TaskSchedulingAutoConfiguration

app:
#  测试环境
#  user-login-url: http://192.168.32.38:8081/oauth/user/login
#  staff-clock-url: http://192.168.32.95:19080/appStaffClockLog/staffClock
#  init-staff-clock-url: http://192.168.32.95:19080/appStaffClockLog/initStaffClock?staffNo=
#  bi-sql-exec-url: http://192.168.32.36:18077/bisql/exec
#  bi-sql-source-id: 22
#  生产环境
  user-login-url: http://server.yuzhilin.net.cn/oauth/user/login
  staff-clock-url: http://server.yuzhilin.net.cn/oa/appStaffClockLog/staffClock
  init-staff-clock-url: http://server.yuzhilin.net.cn/oa/appStaffClockLog/initStaffClock?staffNo=
  bi-sql-exec-url: http://server.yuzhilin.net.cn/bisearchecharts/bisql/exec
  bi-sql-source-id: 5
  select-app-staff-clock-log-sql: "SELECT id,staff_no,clock_time,longitude,latitude,address,clock_type,create_time FROM app_staff_clock_log WHERE staff_no='%s' ORDER BY create_time DESC"
  addresses:
  - id: 1
    address: 北京市海淀区花园东路11号
    longitude: 116.3690760
    latitude: 39.9802720
  - id: 2
    address: 石家庄海河道168号
    longitude: 114.6222430
    latitude: 38.0476450
  - id: 3
    address: 石家庄桥西区物联网大厦c座
    longitude: 114.4414380
    latitude: 38.0165270
  users:
  - user-no: 100245
    username: 王哲
    password: 123456
  - user-no: 100232
    username: 李米盛
    password: 123456
  - user-no: 100226
    username: 刘常富
    password: 123456
  - user-no: 100246
    username: 李贺彦
    password: 123456
  - user-no: 100627
    username: 关晓鹏
    password: 123456
  - user-no: 100230
    username: 张维维
    password: 123456
  - user-no: 100261
    username: 张东丽
    password: 123456

