server:
  port: 8080
  servlet:
    jsp:
      registered: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: enc(F5qYZDfOeGE26wHjxxcAqnxIaXVper1E)
    initialization-mode: never
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    scheduler-name: QuartzScheduler
    properties:
      org.quartz.scheduler.instanceId: AUTO
      org.quartz.jobStore.isClustered: true
      org.quartz.threadPool.class: org.springframework.scheduling.quartz.SimpleThreadPoolTaskExecutor
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.info.ProjectInfoAutoConfiguration
    - org.springframework.boot.autoconfigure.dao.PersistenceExceptionTranslationAutoConfiguration
    - org.springframework.boot.autoconfigure.aop.AopAutoConfiguration
    - org.springframework.boot.autoconfigure.websocket.servlet.WebSocketServletAutoConfiguration
    - org.springframework.boot.autoconfigure.web.servlet.MultipartAutoConfiguration
    - org.springframework.boot.autoconfigure.web.client.RestTemplateAutoConfiguration

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: helloworld
    property:
      prefix: enc(
      suffix: )
