spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    initialization-mode: never
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.info.ProjectInfoAutoConfiguration
    - org.springframework.boot.autoconfigure.dao.PersistenceExceptionTranslationAutoConfiguration
    - org.springframework.boot.autoconfigure.aop.AopAutoConfiguration
