server:
  #应用端口号
  port: 8081
  servlet:
    #应用上下文路径
    context-path: /spring
    jsp:
      registered: false
  ssl:
    enabled: false

spring:
  aop:
    auto: false
  dao:
    exceptiontranslation:
      enabled: false
  jackson:
    #简体中文
    locale: zh_CN
    #北京时间
    time-zone: GMT+8
  mvc:
    publish-request-handled-events: false
  servlet:
    multipart:
      enabled: false
  thymeleaf:
    cache: false
    check-template: false
    check-template-location: false
  messages:
    basename: org.springframework.security.messages,com.example.security.messages
  datasource:
    #数据库用户名
    username: root
    #数据库密码
    password: root
    #数据库连接
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai
    initialization-mode: never
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: never
      table-name: T_USER_SESSION

cas:
  server:
    prefix: http://localhost:8080/cas
    login: ${cas.server.prefix}/login
    logout: ${cas.server.prefix}/logout
  client:
    prefix: http://localhost:${server.port}${server.servlet.context-path}
    login: ${cas.client.prefix}/login/cas
    logout: /logout/cas
