spring:
  application:
    name: mybatis-plus-example
  jmx:
    enabled: false
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.task.TaskSchedulingAutoConfiguration
    - org.springframework.boot.autoconfigure.task.TaskExecutionAutoConfiguration
    - org.springframework.boot.autoconfigure.sql.init.SqlInitializationAutoConfiguration
    - org.springframework.boot.autoconfigure.info.ProjectInfoAutoConfiguration
    - org.springframework.boot.autoconfigure.dao.PersistenceExceptionTranslationAutoConfiguration
    - org.springframework.boot.autoconfigure.ssl.SslAutoConfiguration
  profiles:
    active: local

mybatis-plus:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    return-instance-for-empty-row: true
    jdbc-type-for-null: null
    nullable-on-for-each: true
    arg-name-based-constructor-auto-mapping: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

