spring:
  datasource:
    url: jdbc:mysql://192.168.32.34:3306/yzl_crm2?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: yzl_crm
    password: YZL123456!

