server:
  port: 8082

spring:
  application:
    name: demo-dubbo-consumer
  sql:
    init:
      mode: never
  servlet:
    multipart:
      enabled: false

dubbo:
  registry:
    address: zookeeper://localhost:2181
  application:
    qos-enable: false
    register-mode: instance
    service-discovery:
      migration: FORCE_APPLICATION

