spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

spring.jmx.enabled=false

mybatis.configuration.cache-enabled=false
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.call-setters-on-nulls=true
mybatis.configuration.return-instance-for-empty-row=true
mybatis.configuration.jdbc-type-for-null=null
pagehelper.support-methods-arguments=true
pagehelper.auto-dialect=true
pagehelper.auto-runtime-dialect=true

java.model.package=com.esb.po
sql.map.package=com.esb.mapper
java.client.package=com.esb.mapper
