spring:
  sql:
    init:
      mode: never
  servlet:
    multipart:
      enabled: false
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.ssl.SslAutoConfiguration
    - org.springframework.boot.autoconfigure.info.ProjectInfoAutoConfiguration
    - org.springframework.boot.autoconfigure.dao.PersistenceExceptionTranslationAutoConfiguration
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-returns: true
    dynamic: false

