spring:
  application:
    name: druid-example
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.info.ProjectInfoAutoConfiguration
    - org.springframework.boot.autoconfigure.sql.init.SqlInitializationAutoConfiguration
    - org.springframework.boot.autoconfigure.task.TaskExecutionAutoConfiguration
    - org.springframework.boot.autoconfigure.task.TaskSchedulingAutoConfiguration
    - org.springframework.boot.autoconfigure.ssl.SslAutoConfiguration
    - org.springframework.boot.autoconfigure.jmx.JmxAutoConfiguration
    - org.springframework.boot.autoconfigure.admin.SpringApplicationAdminJmxAutoConfiguration
  datasource:
    url: jdbc:mysql://localhost:3306/example?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

