spring:
  datasource:
    url: jdbc:mysql://localhost:3306/example?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  sql:
    init:
      mode: never
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.auto_quote_keyword: true
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
