spring:
  main:
    web-application-type: none
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.dao.PersistenceExceptionTranslationAutoConfiguration
    - org.springframework.boot.autoconfigure.sql.init.SqlInitializationAutoConfiguration
    - org.springframework.boot.autoconfigure.transaction.TransactionAutoConfiguration
    - org.springframework.boot.autoconfigure.info.ProjectInfoAutoConfiguration
    - org.springframework.boot.autoconfigure.aop.AopAutoConfiguration
    - org.springframework.boot.autoconfigure.web.client.RestTemplateAutoConfiguration
  quartz:
    auto-startup: true
    job-store-type: memory
    properties:
      org.quartz.scheduler.instanceId: AUTO
      org.quartz.threadPool.class: org.springframework.scheduling.quartz.SimpleThreadPoolTaskExecutor

app:
  jgit-job:
    enabled: false
    job-key: job-1
    trigger-key: trigger-1
    cron-expression: '*/10 * * * * ?'
  gitee-job:
    enabled: false
    job-key: job-2
    trigger-key: trigger-2
    cron-expression: '*/10 * * * * ?'
  jgit-config:
    remote-url: https://gitee.com/zww1990/learning-platform.git
    local-directory: d:/projects/learning-platform
    username: 
    author: 
    password: 
    branch-name: master
    date-pattern: yyyyMMdd
    file-pattern: design-pattern-example/src/main/resources
  gitee-config:
    date-pattern: yyyyMMdd
    access-token: 
    owner: zww1990
    repo: learning-platform
    path-format: design-pattern-example/src/main/resources/%s.txt

