spring:
  quartz:
    auto-startup: true
    job-store-type: memory
    properties:
      org.quartz.scheduler.instanceId: AUTO
      org.quartz.threadPool.class: org.springframework.scheduling.quartz.SimpleThreadPoolTaskExecutor

app:
  jgit-job:
    job-key: job-1
    trigger-key: trigger-1
    cron-expression: '*/10 * * * * ?'
    enabled: false
  git-config:
    remote-url: https://gitee.com/zww1990/learning-platform.git
    local-directory: d:/projects/learning-platform
    username: 
    author: 
    password: 
    branch-name: master
    date-pattern: yyyyMMdd
    file-pattern: design-pattern-example/src/main/resources
    create-new-file-url: https://gitee.com/api/v5/repos/zww1990/learning-platform/contents/%s
    access-token: 

