server:
  port: 8081

spring:
  application:
    name: demo-dubbo-provider
  servlet:
    multipart:
      enabled: false
  sql:
    init:
      mode: never

dubbo:
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.example.dubbo.service
  application:
    qos-enable: false
    register-mode: instance
    service-discovery:
      migration: FORCE_APPLICATION

