server:
  port: 8081

spring:
  application:
    name: eureka-server
  sql:
    init:
      mode: never
  servlet:
    multipart:
      enabled: false
  profiles:
    active:
    # 集群模式
#    - cluster
    # 独立模式
    - standalone
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.gson.GsonAutoConfiguration
  security:
    user:
      # 用户名
      name: admin
      # 密码
      password: admin

