server:
  port: 8081

spring:
  application:
    name: eureka-server
  sql:
    init:
      mode: never
  servlet:
    multipart:
      enabled: false
  profiles:
    active: cluster
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.gson.GsonAutoConfiguration

