spring:
  sql:
    init:
      mode: never
  servlet:
    multipart:
      enabled: false
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.ssl.SslAutoConfiguration
    - org.springframework.boot.autoconfigure.info.ProjectInfoAutoConfiguration
    - org.springframework.boot.autoconfigure.dao.PersistenceExceptionTranslationAutoConfiguration
  activemq:
    broker-url: tcp://localhost:61616
    user: user
    password: user
    packages:
      trust-all: true
    pool:
      enabled: true
  jms:
    listener:
      auto-startup: false

