app:
  staff-clock-url: http://192.168.32.95:38080/appStaffClockLog/staffClock
  init-staff-clock-url: http://192.168.32.95:38080/appStaffClockLog/initStaffClock?staffNo=
  create-oa-attend-url: 'http://192.168.32.95:38080/appStaffClockLog/createYesterdayOaAttendTest?staffNos=%s&stratTime=%s&endTime=%s'
  device-list-url: 'http://192.168.32.95:38080/appDeviceRecord/getDeviceList?pageNo=1&pageSize=100&staffNo='
  reset-bind-device-id-url: http://192.168.32.95:38080/appDeviceRecord/resetBindDeviceId
  bi-sql-exec-url: http://192.168.32.36:18066/bisql/exec
  bi-sql-source-id: 22
  users:
  - user-no: 100232
    username: 李米盛
  - user-no: 100226
    username: 刘常富
  - user-no: 100230
    username: 张维维
    enabled: true
    email: zhangweiwei@yuzhilin.net.cn

