server:
  port: 9999

app:
  staff-db-url: http://api.yuzhilin.net.cn/staffDB
  bi-url: http://api.yuzhilin.net.cn/bisearchserver
  bi-sql-source-id: 5
  task:
    cron: '0 30 8,18 ? * MON-FRI'
    am-min: 20
    am-max: 30
    pm-max: 1
    enabled: true
  users:
  - user-no: 100245
    username: 王哲
  - user-no: 100627
    username: 关晓鹏
  - user-no: 100230
    username: 张维维
    enabled: true
    pm-on: true

