spring:
  application:
    name: dgs-example
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.info.ProjectInfoAutoConfiguration
    - org.springframework.boot.autoconfigure.sql.init.SqlInitializationAutoConfiguration
    - org.springframework.boot.autoconfigure.task.TaskExecutionAutoConfiguration
    - org.springframework.boot.autoconfigure.task.TaskSchedulingAutoConfiguration
    - org.springframework.boot.autoconfigure.ssl.SslAutoConfiguration
    - org.springframework.boot.autoconfigure.jmx.JmxAutoConfiguration
    - org.springframework.boot.autoconfigure.admin.SpringApplicationAdminJmxAutoConfiguration
  servlet:
    multipart:
      enabled: false
  web:
    resources:
      static-locations: classpath:/graphiql/

dgs:
  graphql:
    graphiql:
      title: DGS-示例
