server:
  port: 9999

app:
  staff-clock-url: http://api.yuzhilin.net.cn/staffDB/appStaffClockLog/staffClock
  init-staff-clock-url: http://api.yuzhilin.net.cn/staffDB/appStaffClockLog/initStaffClock?staffNo=
  create-oa-attend-url: 'http://api.yuzhilin.net.cn/staffDB/appStaffClockLog/createYesterdayOaAttendTest?staffNos=%s&stratTime=%s&endTime=%s'
  device-list-url: 'http://api.yuzhilin.net.cn/staffDB/appDeviceRecord/getDeviceList?pageNo=1&pageSize=100&staffNo='
  reset-bind-device-id-url: http://api.yuzhilin.net.cn/staffDB/appDeviceRecord/resetBindDeviceId
  bi-sql-exec-url: http://api.yuzhilin.net.cn/bisearchserver/bisql/exec
  bi-sql-source-id: 5
  users:
  - user-no: 100221
    username: 姚辉宇
  - user-no: 100245
    username: 王哲
  - user-no: 100226
    username: 刘常富
  - user-no: 100627
    username: 关晓鹏
  - user-no: 100248
    username: 汪化胜
  - user-no: 100261
    username: 张东丽
  - user-no: 100230
    username: 张维维
  job-config:
    job-key: hello-job
    trigger-key: hello-trigger
    job-data-key: hello-data
    cron-expression: '0 0 9,19 ? * 1-5'

