spring:
  application:
    name: lims-scheduler
    admin:
      enabled: false
  profiles:
    active: prod
  sql:
    init:
      mode: never
  jmx:
    enabled: false
  main:
    banner-mode: off
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.dao.PersistenceExceptionTranslationAutoConfiguration
      - org.springframework.boot.autoconfigure.info.ProjectInfoAutoConfiguration

mybatis:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    return-instance-for-empty-row: true
    jdbc-type-for-null: null
    nullable-on-for-each: true
    arg-name-based-constructor-auto-mapping: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/**/*.xml

