server:
  port: 44444

spring:
  multi:
    datasources:
      FIRST:
        jdbc-url: jdbc:mysql://172.24.13.29:3306/lims_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: oper_dc
        password: nq4P6URP44unRtr
        connection-test-query: select 1
        max-lifetime: 600000
      SECOND:
        jdbc-url: jdbc:oracle:thin:@10.32.1.132:1521:lims
        username: lims
        password: limsxt
        connection-test-query: select 1 from dual
        max-lifetime: 600000
  task:
    scheduling:
      pool:
        size: 8

jobs:
  from-temporarysampling-to-limslsjy:
    cron: 0 7,17,27,37,47,57 * * * *
    enabled: true
  demo:
    cron: 0/10 * * * * *
    enabled: false

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
