spring:
  application:
    name: reactive-example
  sql:
    init:
      mode: never
  r2dbc:
    url: r2dbc:mysql://localhost:3306/example?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.info.ProjectInfoAutoConfiguration
    - org.springframework.boot.autoconfigure.ssl.SslAutoConfiguration
    - org.springframework.boot.autoconfigure.web.reactive.ReactiveMultipartAutoConfiguration
    - org.springframework.boot.autoconfigure.jmx.JmxAutoConfiguration
    - org.springframework.boot.autoconfigure.admin.SpringApplicationAdminJmxAutoConfiguration

