server:
  port: 8081

spring:
  application:
    name: demo-dubbo-provider
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  rabbitmq:
    host: localhost
    port: 5672
    username: 
    password: 
    virtual-host: 
    publisher-returns: true

dubbo:
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.example.dubbo.service
  application:
    register-mode: instance
    service-discovery:
      migration: FORCE_APPLICATION

rabbitmq:
  enable: false
