package com.example.hibernate.model;
// Generated 2017-2-27 18:33:05 by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ZDoubanFilm generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "z_douban_film")
public class ZDoubanFilm implements java.io.Serializable {

	private String filmId;
	private String filmName;
	private String year;
	private String writers;
	private String types;
	private String countries;
	private String languages;
	private String pubdates;
	private String durations;
	private String alias;
	private String summary;
	private String score;
	private String star;
	private String votecount;
	private String tag;

	public ZDoubanFilm() {
	}

	public ZDoubanFilm(String filmId) {
		this.filmId = filmId;
	}

	public ZDoubanFilm(String filmId, String filmName, String year, String writers, String types, String countries,
			String languages, String pubdates, String durations, String alias, String summary, String score,
			String star, String votecount, String tag) {
		this.filmId = filmId;
		this.filmName = filmName;
		this.year = year;
		this.writers = writers;
		this.types = types;
		this.countries = countries;
		this.languages = languages;
		this.pubdates = pubdates;
		this.durations = durations;
		this.alias = alias;
		this.summary = summary;
		this.score = score;
		this.star = star;
		this.votecount = votecount;
		this.tag = tag;
	}

	@Id
	@Column(name = "film_id", unique = true, nullable = false)
	public String getFilmId() {
		return this.filmId;
	}

	public void setFilmId(String filmId) {
		this.filmId = filmId;
	}

	@Column(name = "film_name")
	public String getFilmName() {
		return this.filmName;
	}

	public void setFilmName(String filmName) {
		this.filmName = filmName;
	}

	@Column(name = "year")
	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	@Column(name = "writers")
	public String getWriters() {
		return this.writers;
	}

	public void setWriters(String writers) {
		this.writers = writers;
	}

	@Column(name = "types")
	public String getTypes() {
		return this.types;
	}

	public void setTypes(String types) {
		this.types = types;
	}

	@Column(name = "countries")
	public String getCountries() {
		return this.countries;
	}

	public void setCountries(String countries) {
		this.countries = countries;
	}

	@Column(name = "languages")
	public String getLanguages() {
		return this.languages;
	}

	public void setLanguages(String languages) {
		this.languages = languages;
	}

	@Column(name = "pubdates")
	public String getPubdates() {
		return this.pubdates;
	}

	public void setPubdates(String pubdates) {
		this.pubdates = pubdates;
	}

	@Column(name = "durations")
	public String getDurations() {
		return this.durations;
	}

	public void setDurations(String durations) {
		this.durations = durations;
	}

	@Column(name = "alias")
	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	@Column(name = "summary")
	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	@Column(name = "score")
	public String getScore() {
		return this.score;
	}

	public void setScore(String score) {
		this.score = score;
	}

	@Column(name = "star")
	public String getStar() {
		return this.star;
	}

	public void setStar(String star) {
		this.star = star;
	}

	@Column(name = "votecount")
	public String getVotecount() {
		return this.votecount;
	}

	public void setVotecount(String votecount) {
		this.votecount = votecount;
	}

	@Column(name = "tag")
	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

}
