spring:
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.info.ProjectInfoAutoConfiguration
    - org.springframework.boot.autoconfigure.sql.init.SqlInitializationAutoConfiguration
    - org.springframework.boot.autoconfigure.task.TaskExecutionAutoConfiguration
    - org.springframework.boot.autoconfigure.task.TaskSchedulingAutoConfiguration
    - org.springframework.boot.autoconfigure.aop.AopAutoConfiguration

app:
  read-folder: D:\待合并的工作簿
  write-folder: D:\已合并的工作簿
  date-time-pattern: yyyy-MM-dd_HH-mm-ss

