app:
  staff-db-url: http://192.168.32.95:38080
  bi-url: http://192.168.32.36:18066
  bi-sql-source-id: 22
  task:
    cron: '*/10 * * * * ?'
    am-max: 30
    pm-max: 30
    enabled: false
  users:
  - user-no: 100232
    username: 李米盛
  - user-no: 100226
    username: 刘常富
  - user-no: 100230
    username: 张维维
    enabled: true
    pm-on: true

